version: '3.6'
services:
  db:
    image: "postgres:11.5"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    env_file:
      - env_file
  flaskapp:
    build: ./backend
    user: ${CURRENT_USER}
    env_file:
      - env_file
    volumes:
      - ./backend:/app
    depends_on:
      - db
  frontend:
    image: "node:10.16.3-alpine"
    command: ["/code/entry.sh"]
    user: ${CURRENT_USER}
    volumes:
      - ./frontend:/code
      - ./backend/yangify/static:/output
volumes:
  dbdata:
