version: '3.6'
services:
  db:
    image: "postgres:11.5"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    env_file:
      - env_file
  flaskapp:
    build: ./backend
    user: ${CURRENT_USER}
    env_file:
      - env_file
    volumes:
      - ./backend:/app
    depends_on:
      - db
  frontend:
    image: "node:10.16.3-alpine"
    command: ["/code/entry.sh"]
    user: ${CURRENT_USER}
    volumes:
      - ./frontend:/code
  collectstatic:
    image: "python:3.7.4-buster"
    command: ["python", "-u", "/code/collect.py"]
    user: ${CURRENT_USER}
    volumes:
      - ./collectstatic:/code
      - ./frontend/dist:/statics/dist
      - ./backend/yangify/static:/statics/media
  nginx:
    image: "nginx:1.13.5"
    ports:
      - "8080:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./collectstatic/output:/etc/nginx/html/static
    depends_on:
      - flaskapp
      - collectstatic
volumes:
  dbdata:
