"""empty message

Revision ID: 1065b18dfd4c
Revises: d23d847b60db
Create Date: 2019-08-28 18:36:17.240655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1065b18dfd4c'
down_revision = 'd23d847b60db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('explainer', sa.Column('slug', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('explainer', 'slug')
    # ### end Alembic commands ###
