"""empty message

Revision ID: 66e62baae5ea
Revises: 2b91c4f7fd66
Create Date: 2019-09-01 18:40:43.884931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66e62baae5ea'
down_revision = '2b91c4f7fd66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('explainer', 'views',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('explainer', 'views',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
