"""empty message

Revision ID: 68eab8ba8e02
Revises: 
Create Date: 2019-08-22 04:11:42.125544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68eab8ba8e02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('google_user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('identifier')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('google_user')
    op.drop_table('user')
    # ### end Alembic commands ###
