"""empty message

Revision ID: 6ab6e0ae3080
Revises: ad0be8b0193c
Create Date: 2019-08-22 19:02:36.659542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ab6e0ae3080'
down_revision = 'ad0be8b0193c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('explainer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question')
    )
    op.create_table('explainer_video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('explainer_id', sa.Integer(), nullable=False),
    sa.Column('video_provider', sa.Text(), nullable=False),
    sa.Column('video_id', sa.Text(), nullable=False),
    sa.Column('start', sa.Text(), nullable=False),
    sa.Column('end', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['explainer_id'], ['explainer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('explainer_video')
    op.drop_table('explainer')
    # ### end Alembic commands ###
