"""empty message

Revision ID: 6e563ef88e63
Revises: f1d516fc54d1
Create Date: 2019-09-01 18:33:03.686933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e563ef88e63'
down_revision = 'f1d516fc54d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('explainer', sa.Column('views', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('explainer', 'views')
    # ### end Alembic commands ###
