"""empty message

Revision ID: 709f185ccfe1
Revises: 0d917e6908da
Create Date: 2019-08-28 19:01:44.943128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '709f185ccfe1'
down_revision = '0d917e6908da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('explainer', 'slug',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('explainer', 'slug',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
