"""empty message

Revision ID: 7866b0caf36a
Revises: ab85ce318d0b
Create Date: 2019-08-23 02:45:18.906895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7866b0caf36a'
down_revision = 'ab85ce318d0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_approver', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_approver')
    # ### end Alembic commands ###
