"""empty message

Revision ID: ab85ce318d0b
Revises: 59e826453f27
Create Date: 2019-08-23 02:40:49.028700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab85ce318d0b'
down_revision = '59e826453f27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('explainer', sa.Column('pending', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('explainer', 'pending')
    # ### end Alembic commands ###
