"""empty message

Revision ID: ad0be8b0193c
Revises: 68eab8ba8e02
Create Date: 2019-08-22 05:03:15.729197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad0be8b0193c'
down_revision = '68eab8ba8e02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('google_user', sa.Column('profile_pic', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('google_user', 'profile_pic')
    # ### end Alembic commands ###
