"""empty message

Revision ID: d23d847b60db
Revises: dba6a43be576
Create Date: 2019-08-24 20:32:23.568792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd23d847b60db'
down_revision = 'dba6a43be576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('explainer', sa.Column('submitter_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'explainer', 'user', ['submitter_id'], ['id'])
    op.drop_constraint('explainer_video_submitter_id_fkey', 'explainer_video', type_='foreignkey')
    op.drop_column('explainer_video', 'submitter_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('explainer_video', sa.Column('submitter_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('explainer_video_submitter_id_fkey', 'explainer_video', 'user', ['submitter_id'], ['id'])
    op.drop_constraint(None, 'explainer', type_='foreignkey')
    op.drop_column('explainer', 'submitter_id')
    # ### end Alembic commands ###
