"""empty message

Revision ID: dba6a43be576
Revises: 131cbe6fbce2
Create Date: 2019-08-24 20:31:17.236624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dba6a43be576'
down_revision = '131cbe6fbce2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('explainer_video', sa.Column('submitter_id', sa.Integer(), nullable=False))
    op.drop_constraint('explainer_video_submitter_fkey', 'explainer_video', type_='foreignkey')
    op.create_foreign_key(None, 'explainer_video', 'user', ['submitter_id'], ['id'])
    op.drop_column('explainer_video', 'submitter')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('explainer_video', sa.Column('submitter', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'explainer_video', type_='foreignkey')
    op.create_foreign_key('explainer_video_submitter_fkey', 'explainer_video', 'user', ['submitter'], ['id'])
    op.drop_column('explainer_video', 'submitter_id')
    # ### end Alembic commands ###
