"""empty message

Revision ID: f31c538652b7
Revises: 66e62baae5ea
Create Date: 2019-09-07 14:53:47.254688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f31c538652b7'
down_revision = '66e62baae5ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('explainer_video', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('explainer_video', 'description')
    # ### end Alembic commands ###
